# Configuración global para Prometheus
global:
  # Intervalo de scrapes (cada cuánto Prometheus recoge métricas)
  scrape_interval: 15s  # 15 segundos

# Configuración de los trabajos de scrapping
scrape_configs:
  - job_name: 'prometheus'  # Nombre del job o tarea

    # Configuración de los targets estáticos
    static_configs:
      - targets: ['localhost:9090']  # Lista de endpoints a monitorear
